mahsulot = input()
narx = int(input())
soni = int(input())
jami = narx * soni
print("===== CHEK =====")
print(f"Mahsulot: {mahsulot}")
print(f"Narx: {narx}")
print(f"Soni: {soni}")
print(f"Jami: {jami}")
print("================")